### ISSUE TITLE
Wrong title on Review and Confirmation pages for manageIdentity

### ISSUE THREAD

**Issue by AMIRKHANEF** [PolkaGate/polkagate-extension#840]
![InkedScreenshot 2023-08-18 at 18 44 24](https://github.com/PolkaGate/polkagate-extension/assets/75857984/4d4f8360-4196-42a7-96e7-e5993b672bec)

**Comment by Nick-1979** [comment]
@AMIRKHANEF do you want to send a PR for this?

**Comment by AMIRKHANEF** [comment]
@Nick-1979 Of course, I will submit a pull request to address this issue as soon as I have completed the SocialRecovery.
