### ISSUE TITLE
close stake option popUp on chain change

### ISSUE THREAD

**Issue by Nick-1979** [PolkaGate/polkagate-extension#873]
If staking option popover is open, and chain is changed to a non-consistent chain, .... bug!

**Comment by AMIRKHANEF** [comment]
![image](https://github.com/PolkaGate/polkagate-extension/assets/75857984/645f3edc-0449-4251-8157-9d41f13974c9)

Are you referring to this page?
I've observed that when you're in full-screen mode on the solo or pool staking pages and you switch to a chain from the extension that doesn't support them, it causes a bug.
